# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container to /app
WORKDIR /app

# Add /app to the system path for python
ENV PYTHONPATH="${PYTHONPATH}:/app"

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Run the unit tests when the container launches
CMD ["python", "-m", "unittest", "discover"]
